services:
  demo:
    image: node:20-alpine
    working_dir: /app

    volumes:
      - ./:/app

    entrypoint: ["npm", "start"]

    ports:
      - 3002:3000
      - 3003:3003

    env_file:
      - .env.test
      # - .env.local
      # - test-proxy-port-swap.env
      # - local-proxy-port-swap.env
      # - test-proxy.env
      # - local-proxy.env
      # - local.env
      # - test.env
